language: c
services:
    - docker

matrix:
    include:
        - env: ITEST_TARGET=itest_trusty
        - env: ITEST_TARGET=itest_xenial
        - env: ITEST_TARGET=itest_bionic
        - env: ITEST_TARGET=itest_stretch
        - env: ITEST_TARGET=itest_tox
        - os: linux-ppc64le
          env: ITEST_TARGET=itest_stretch
    allow_failures:
        - os: linux-ppc64le
          env: ITEST_TARGET=itest_stretch


script:
   - make "$ITEST_TARGET"

after_script:
   - ci/artifact-upload
