#!/bin/bash -eux
if [ "$#" -eq 1 ]; then
    dumb_init_bin=$(readlink -f "$1")
else
    dumb_init_bin=$(which dumb-init) || {
        echo "Couldn't find dumb-init on your path, exiting."
        exit 1
    }
fi

echo "Running with dumb-init at '$dumb_init_bin'"

run_tests() {
    ./test-tty "$dumb_init_bin"
    
    export DUMB_INIT_PROCESS_GROUP
    for DUMB_INIT_PROCESS_GROUP in 0 1; do
        ./test-proxies-signals "$dumb_init_bin"
        ./test-exit-status "$dumb_init_bin"
        ./test-help-message "$dumb_init_bin"
    done

    DUMB_INIT_PROCESS_GROUP=0 ./test-pgroup "$dumb_init_bin" 4
    DUMB_INIT_PROCESS_GROUP=1 ./test-pgroup "$dumb_init_bin" 0
}

cd tests

echo "Running tests in normal mode."
run_tests

echo "Running tests in debug mode."
export DUMB_INIT_DEBUG=1
run_tests
