#!/bin/bash -euxm
# dumb-init should not proxy signals to a process group rooted at its child if
# asked not to.
dumb_init="$1"

DUMB_INIT_PROCESS_GROUP=0 $dumb_init nohup sh -c "yes 'oh, hi' | tail & yes error | tail >&2" > /dev/null &
pid="$!"

sleep 1
shell_pid=$(pgrep -P "$pid")
child_pids=$(pgrep -P $shell_pid)

kill -TERM "$pid"
sleep 1

# ensure all processes are still running
while read pid; do
    if pgrep "$pid"; then
        echo "Error: expected process $pid to still be alive, but it wasn't."
        exit 1
    else
        echo "Process $pid was still alive (as expected)."
    fi
done <<< "$child_pids"
xargs kill -9 <<< "$child_pids"
