#!/usr/bin/env python
EOF = b'\x04'


def ttyflags(fd):
    # see: http://www.gnu.org/software/libc/manual/html_mono/libc.html#Output-Modes
    import termios as T
    attrs = T.tcgetattr(fd)
    attrs[1] &= ~T.OPOST  # don't munge output
    attrs[3] &= ~T.ECHO  # don't echo input
    T.tcsetattr(fd, T.TCSANOW, attrs)


def child(dumb_init):
    from os import execvp
    execvp('timeout', ('timeout', '1', dumb_init, 'tac'))


def parent(fd):
    ttyflags(fd)
    from os import read, write
    assert write(fd, b'1\n2\n3\n') == 6
    assert write(fd, EOF * 2) == 2
    output = read(fd, 1 << 10)
    assert output == b'3\n2\n1\n', repr(output)
    print('PASS')


def test_tty(dumb_init):
    import pty
    pid, fd = pty.fork()
    if pid == 0:
        child(dumb_init)
    else:
        parent(fd)


def main():
    from os import environ
    environ['DUMB_INIT_DEBUG'] = '0'
    from sys import argv
    test_tty(argv[1])


main()
