#!/bin/bash -eux
dumb_init="$1"

# dumb-init should exit with the same exit status as the process it launches.
for i in 0 1 2 32 64 127 254 255; do
    status=$($dumb_init sh -c "exit $i"; echo $?)

    if [ "$status" -ne "$i" ]; then
        echo "Error: Expected exit status $i, got $status."
        exit 1
    fi
done
