#!/bin/sh -eu
# Print received signals into a file, one per line
file="$1"

. ./lib/testlib.sh

for i in $(catchable_signals); do
	trap "echo $i > \"$file\"" "$i"
done

echo 'ready' > "$file"

# loop forever
while :; do true; done
