#!/bin/sh -eux
# XXX: We use /bin/sh instead of /bin/bash since some old versions of bash
# exhibit an issue where they seem to receive the same signal twice.
# With /bin/sh, this does not seem to happen.

# Print received signals into a file, one per line
here="$(dirname $(readlink -f $0))"
file="${1:-/dev/stdout}"

. $here/testlib.sh

prev_signal=0
handle() {
    echo "[print-signals] got signal $1"
    if [ "$prev_signal" -eq "$1" -a "$1" -eq 2 ]; then
        echo "[print-signals] got INT twice. exiting."
        exit 0
    else
        prev_signal="$1"
    fi
}

for i in $(catchable_signals); do
    trap "handle $i > \"$file\"" "$i"
done

echo '[print-signals] ready' > "$file"

echo '[print-signals] loop forever...'
set +x
while :; do true; done
