#!/bin/bash -eux
set -o pipefail

. /mnt/ci/docker

python setup.py clean
python setup.py sdist
pip install --upgrade setuptools distribute
pip install -vv dist/*.tar.gz
pip install -r requirements-dev.txt
py.test tests/

exec dumb-init /mnt/tests/test-zombies \
