#!/bin/bash -eux
set -euo pipefail

cd /mnt

python3 setup.py clean
python3 setup.py sdist
pip3 install -vv dist/*.tar.gz
pip3 install -r requirements-dev.txt
pytest-3 -vv tests/

exec dumb-init /mnt/tests/test-zombies
