#!/bin/bash -eux
set -o pipefail

# Allow pip from modifying the system packages
export PIP_BREAK_SYSTEM_PACKAGES=1

apt-get update
apt-get -y --no-install-recommends install python3-pip procps

cd /mnt
dpkg -i dist/*.deb
pip3 install -r requirements-dev.txt
pytest tests/

exec dumb-init /mnt/tests/test-zombies
